storage_account_name        = "saanvikit2023sa"
public_ip_name              = "saanvikit-pip"
network_security_group_name = "saanvikit-nsg"
network_interface_name      = "saanvikit-nic"
virtual_machine_name        = "saanvikit-vm"
